# Site Info
title: Copluk
tagline: 'Sub Title'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: http://copluk.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Copluk
  description: 個人介紹
  gravatar:  # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/
    github:    https://github.com/
    facebook:  https://www.facebook.com/loki2085
    email:     http://www.google.com/

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
    
  # Github Project: 
  #   - 'http://copluk.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Puglins
mathjax: false # whether support mathjax
# google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
# disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

