# Site Info
title: Copluk
tagline: 'Life & Code'
description: ''
baseurl: ""
url: https://copluk.github.io
logo: '/public/logo.png'

# Site configurations
gem: 'jekyll-paginate'
group: :jekyll_plugins
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Copluk
  description: 知識沒有盡頭的軟體生活
  gravatar: c3f92aa6c29c353ebe256b670e5b9241
  mail: c.xu2085@gmail.com
  contact:
    linkedin:  https://www.linkedin.com/in/Copluk
    github:    https://github.com/copluk
    # facebook:  https://www.facebook.com/loki2085
    # email:     c.xu2085@gmail.com

# Navigation (2nd level links supported)
nav:
  About:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  # About:          
  #   - '/about/'

  # Github Project: 
  #   - 'http://copluk.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Puglins
mathjax: false # whether support mathjax
google_analytics_token: 'UA-102429388-1' # leave blank if you don't want google analytics
disqus_short_name: 'coplukgitpage' # leave blank if you don't want disqus

